### ISSUE TITLE
[Feature] 禁止用户删除邮件（可配置）

### ISSUE THREAD

**Issue by lwd-temp** [dreamhunter2333/cloudflare_temp_email#163]
## 请描述您的 Feature

禁止用户删除邮件，可通过环境变量配置。

## 描述您想要的解决方案

当配置项为true时，非管理员无法删除邮件，提示not allowed。

**Comment by dreamhunter2333** [comment]
好的，我添加个配置项

**Comment by dreamhunter2333** [comment]
已新增配, [文档链接](https://temp-mail-docs.awsl.uk/zh/guide/cli/worker.html#:~:text=%23%20%E5%85%81%E8%AE%B8%E7%94%A8%E6%88%B7%E5%88%A0%E9%99%A4%E9%82%AE%E4%BB%B6%2C%20%E4%B8%8D%E9%85%8D%E7%BD%AE%E5%88%99%E4%B8%8D%E5%85%81%E8%AE%B8%0AENABLE_USER_DELETE_EMAIL%20%3D%20true%0A%23%20%E5%85%81%E8%AE%B8%E8%87%AA%E5%8A%A8%E5%9B%9E%E5%A4%8D%E9%82%AE%E4%BB%B6%0AENABLE_AUTO_REPLY%20%3D%20false)

```toml
# 允许用户删除邮件, 不配置则不允许
ENABLE_USER_DELETE_EMAIL = true
# 允许自动回复邮件
ENABLE_AUTO_REPLY = false
```
